// `all-contributors` types
// Copied from https://github.com/all-contributors/app/blob/master/lib/parse-comment.js#L4
export const ALL_CONTRIBUTORS_TYPES = [
  'a11y',
  'audio',
  'blog',
  'bug',
  'business',
  'code',
  'content',
  'data',
  'design',
  'doc',
  'eventorganizing',
  'example',
  'financial',
  'fundingfinding',
  'ideas',
  'infra',
  'maintenance',
  'mentoring',
  'platform',
  'plugin',
  'projectManagement',
  'promotion',
  'question',
  'research',
  'review',
  'security',
  'talk',
  'test',
  'tool',
  'translation',
  'tutorial',
  'usertesting',
  'video',
]
