language: node_js
node_js: '11'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.10.0'
    - node_js: '11'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'JerjwGxPL++EORydSXd9uPazX2kJvLf9V1ZjvKTA9xr32KAEFhHr1lIIXgljVLY/5KZkw3hOL3aSJcQ5wF5v3xepQ+oZ0SHj2HCLKZvrglO3FEFuwtO1QegD5zuaq2JvypLSDrain72ZKLuRz0W7uMrXy0qJ54O0Hqjyfy7hIUVksN8DzJbarG/oxzLJEpkbgwIXUeTyAB7HjRxiz0vWLp2t0HrYxIiH43FsvMBqkLV+tvxVaRv5lKvFWVeaEVHoG89skAkhWtUKeHkfY8/FfrWu55wjYsmiQMWfOUg6J3nT9FGD67xxOFACHjBKs6CVEKvk/DS+RLBx/vHC6UyNxp93NlqHA6cTJS/MW8d5gUAhchCk1QCbiKu9kZg5y3IDNxR0Ry+Enbu308s+9GIfTci4FXm/8IQDutWkRToy5D3McLCfG5lQAM0voU0X6v/E59WHRy0Qte8uGIMftU1os6BmvG/9UclLw+xXSSBVphvdp6XqMP9iNHQ8UXNhhkQA5hzryrkdnGXc7NuLRHvCpiHHSIXfTKSpBVSkmxCxuUYko9RoaWJF8GxxBEsoj+q4KDVm5bNwO1wwpo9455YQDaIY5y1lK8IzKfV96e+7yoJ8V2idE0My42FezY7gerKehZhf+pi2zoRiphSkolntXyDkNGkbozjag+YxwLNWc2M='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
