language: node_js
node_js: '11'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.10.0'
    - node_js: '10'
    - node_js: '11'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: "UpIy1NS0P1guxq+vNG6/oLX2574dWt0XSjKKazrvsHCUaX/dKRIsDSLqom4fkm97n2HXIGcPFndJka9bmQxDvMPXbQyBrzWhGRLSuKt9nc4g78hbUdrjBpZlxe5J0cRhnG9EuQ6LS7g2w2jg6gsrVX+fwdqoYSzbDO3djC0xIPDB7uwmsjYs3h4kaADRSlq24oZFqEEPZO9BLo7ecQl6qEi0XClZOCI6YyFtJPX7OCxmts3tudpgxfNxgpPi905K0mcX2xw5KtRJ212Yxt40Vax8Hb8XulmKm2F2N8G0h33KCqG8b8mOeNjLL2ASGdSO+qWdBPOC+q+DuI58ukob/fn+gRgM3CLVvuJ0HuqHmFAvtGpuMYKXDuPfkzE6OesnZPcr280WXdTS4J9X/ZB6fZio2nmu3cfAtdhFV1KLQU0oCXGI2YtjxA56W0jOr3n4ffNxY0xhS0MScuaGrFq9xtQanz/EMroZPSSypgCJc4sA69sLIHKDVrIuQ0jilpFL/Z6p3NK0ihq2t33aNXDvfwAnKDFXa3tRRV8ey7gyse7u8k4Bb8Vx7VY8d/j3nN+M1vD+4930TAEwA74wCOUmxzMEMXKWegfSm28gwKwHWiCcHU6TlyUt6UDnun2zgPKbxUiaHlJACDpmbYzfKh4VV66p9kXJQ3t8jIAUDohQdGE="
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
