name: Build
on: workflow_call
env:
  codecov_token: ${{ secrets.CODECOV_TOKEN }}
jobs:
  combinations:
    name: ${{ matrix.os }}, Node.js ${{ matrix.node }}
    # git push --tags does not create any commits so should not trigger a new
    # workflow. There are no ways to skip workflows, so we skip jobs instead
    if: toJson(github.event.commits) != '[]'
    strategy:
      # Test on Windows/Mac/Linux using latest Node.js.
      # Also test on Linux with older Node.js versions.
      # We do not run each possible combination to make CI faster.
      matrix:
        os: [ubuntu, macOS, windows]
        node: [23]
        include:
          - os: ubuntu
            node: 18.18.0
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx gulp build
      - name: Lint
        run: npx gulp check
      - name: Check types
        run: npx gulp type
      - name: Test
        if: ${{ env.codecov_token == '' }}
        run: npx gulp unit
      - name: Restore links cache
        if: ${{ matrix.node == 23 && matrix.os == 'ubuntu' }}
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Check links
        if: ${{ matrix.node == 23 && matrix.os == 'ubuntu' }}
        run: npx gulp links
      # If the CODECOV_TOKEN secret is set, perform test coverage
      - name: Test and coverage
        if: ${{ env.codecov_token != '' }}
        run: npx gulp unitCoverage
      - name: Upload test coverage
        if: ${{ env.codecov_token != '' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.codecov_token }}
          flags: '${{ matrix.os }}, node-${{ matrix.node }}'
          verbose: true
